contact:
    path:       /{_locale}/contact
    controller: App\Controller\BlogController::contact
    requirements:
        _locale: '%app.locales%'
#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number

#some_route:
#    path:       /%app.route_prefix%/contact
#    controller: App\Controller\MainController::contact

generating-url:
    path: /generatingUrl/{slug}
    controller: App\Controller\BlogController::generatingUrl

session:
    path: /session
    controller: App\Controller\BlogController::session